import reflex as rx

from ..ui import navbar

def startherepage() -> rx.Component:
    # Welcome Page (Index)
    return rx.flex(
        navbar(),
        hero_section(),
        #footer(),
        direction="column",
        justify="center",
        align="center",
        background_color="#ffffff",
        height="100vh",
    )

def hero_section() -> rx.Component:
    return rx.flex(
        rx.flex(
            rx.flex(
                rx.text(
                    "No que acreditamos;",
                    text_align="left",
                    #background_image="linear-gradient(95deg, #D6D6ED 42.14%, #727280 63.21%)",
                    font_size="30px",
                    #background_clip="text",
                    font_weight="bold",
                    line_height="1",
                    font_family= "Garamond",
                    #background_color="#000000",
                    color="#000000",  
                    width="100%",
                ),
                rx.flex(
                    rx.text(
                        "Se você está lendo isso, provavelmente busca alguma ajuda. Essa plataforma é para você.",
                        text_align="left",
                        color="#000000", 
                        #background_color="#000000",
                        font_size="15px",
                        font_weight="regular",
                        line_height="1.5",
                        width="80%",
                    ),
                    rx.text(
                        "Há pouco mais de 6 anos fui diagnosticado com depressão. De lá para cá, os anos têm sido turbulentos. Talvez você esteja passando por algo similar.",
                        text_align="left",
                        color="#000000", 
                        #background_color="#000000",
                        font_size="15px",
                        font_weight="regular",
                        line_height="1.5",
                        width="80%",
                    ),
                    rx.text(
                        "Sei que não é fácil navegar por tudo isso: Reconhecer e aceitar o seu momento, buscar ajuda, iniciar um tratamento, persistir no tratamento, compartilhar suas questões com outras pessoas, etc.",
                        text_align="left",
                        color="#000000", 
                        #background_color="#000000",
                        font_size="15px",
                        font_weight="regular",
                        line_height="1.5",
                        width="80%",
                    ),
                    rx.text(
                        "Inúmeras são as dificuldades nessa jornada. Tendo passado por muitas delas, vejo que podemos fazer melhor por quem precisa de ajuda.",
                        text_align="left",
                        color="#000000", 
                        #background_color="#000000",
                        font_size="15px",
                        font_weight="regular",
                        line_height="1.5",
                        width="80%",
                    ),
                    rx.text(
                        "A partir disso, surgiu o desejo por construir algo que te ajude a...",
                        text_align="left",
                        color="#000000", 
                        #background_color="#000000",
                        font_size="15px",
                        font_weight="regular",
                        line_height="1.5",
                        width="80%",
                    ),
                    rx.text(
                        ".......finish later......",
                        text_align="left",
                        color="#000000", 
                        #background_color="#000000",
                        font_size="15px",
                        font_weight="regular",
                        line_height="1.5",
                        width="80%",
                    ),
                    direction="column",
                    spacing='2',
                    justify='between',
                    align='stretch',
                ),
                spacing="4",
                direction='column',
                width="50vw",
            ),
            rx.flex(
                rx.text(
                    "Norteadores;",
                    text_align="left",
                    font_size="30px",
                    font_weight="bold",
                    line_height="1",
                    font_family= "Garamond",
                    color="#000000",  
                    width="100%",
                ),
                rx.flex(
                    rx.text(
                        "Saúde acima de lucro: xxxxxx",
                        text_align="left",
                        color="#000000", 
                        font_size="15px",
                        font_weight="regular",
                        line_height="1.5",
                        width="80%",
                    ),
                    rx.text(
                        "Tecnologia como ferramenta: xxxxxx",
                        text_align="left",
                        color="#000000", 
                        font_size="15px",
                        font_weight="regular",
                        line_height="1.5",
                        width="80%",
                    ),
                    rx.text(
                        "Foco no que é essencial: xxxxxx",
                        text_align="left",
                        color="#000000", 
                        font_size="15px",
                        font_weight="regular",
                        line_height="1.5",
                        width="80%",
                    ),
                    rx.text(
                        "Colaboração: xxxxxx",
                        text_align="left",
                        color="#000000", 
                        font_size="15px",
                        font_weight="regular",
                        line_height="1.5",
                        width="80%",
                    ),
                    direction="column",
                    spacing='2',
                    justify='between',
                    align='stretch',
                ),
                spacing="4",
                direction="column",
                width="50vw",
            ),
            direction='row',
            width="100vw",
        ),
        rx.link(
            rx.button(
                "Conhecer",
                font_size="15px",
                size="3",
                weight="bold",
                variant="solid",
                radius="full",
                background_color=rx.color("gray", 12),
                high_contrast=False,
            ),
            href="/chatpage",
        ),
        spacing="4",
        direction="column",
        height="100vh",
        width="100vw",
        justify="start",
        align='stretch',
        padding="5em",
    )
